version: '3'

services:
  mongodb:
    image: mongo
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: TOIoaidsjf123
    ports:
      - 27017:27017

volumes:
  mongodb: